# -*- coding: utf-8 -*-
"""Neural network-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kz_zx489yC7FhwiO_9uvKoI3FdGg9VAr
"""

# -*- coding: utf-8 -*-
"""Neural-network-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7VaSimZh2DMrGCMlqjNOuSAssEFXYph
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os


# UNIT I: DATA PROCESSING


def load_and_preprocess_data():
    """Load MNIST, normalize, flatten, one-hot encode, and split."""
    print("=" * 60)
    print("UNIT I: Data Processing")
    print("=" * 60)

    # Load MNIST via TensorFlow
    import tensorflow as tf
    (X_train_raw, y_train_raw), (X_test_raw, y_test_raw) = tf.keras.datasets.mnist.load_data()

    print(f"Raw training set shape : {X_train_raw.shape}")
    print(f"Raw test set shape     : {X_test_raw.shape}")
    print(f"Pixel value range      : [{X_train_raw.min()}, {X_train_raw.max()}]")

    # Step 1: Normalize pixel values from [0,255] to [0.0,1.0]
    X_train_norm = X_train_raw / 255.0
    X_test_norm  = X_test_raw  / 255.0

    # Step 2: Flatten 28x28 images into 784, dim vectors
    X_train_flat = X_train_norm.reshape(X_train_norm.shape[0], -1)   # (60000, 784)
    X_test_flat  = X_test_norm.reshape(X_test_norm.shape[0],  -1)    # (10000, 784)

    # Step 3: One-hot encode labels (10 classes)
    def one_hot(labels, num_classes=10):
        n = labels.shape[0]
        oh = np.zeros((n, num_classes))
        oh[np.arange(n), labels] = 1.0
        return oh

    Y_train_oh = one_hot(y_train_raw)
    Y_test_oh  = one_hot(y_test_raw)

    # Step 4: Split training into train + validation (80/20)
    split = int(0.8 * X_train_flat.shape[0])   # 48000 train, 12000 val
    X_train, X_val = X_train_flat[:split], X_train_flat[split:]
    Y_train, Y_val = Y_train_oh[:split],   Y_train_oh[split:]
    y_train_labels = y_train_raw[:split]
    y_val_labels   = y_train_raw[split:]

    print(f"\nAfter preprocessing:")
    print(f"  X_train : {X_train.shape}  |  Y_train : {Y_train.shape}")
    print(f"  X_val   : {X_val.shape}    |  Y_val   : {Y_val.shape}")
    print(f"  X_test  : {X_test_flat.shape}   |  Y_test  : {Y_test_oh.shape}")

    # Visualize sample images
    fig, axes = plt.subplots(2, 10, figsize=(15, 3.5))
    fig.suptitle("MNIST Sample Images (One per Class)", fontsize=13, fontweight='bold')
    for digit in range(10):
        idx = np.where(y_train_raw == digit)[0][0]
        axes[0, digit].imshow(X_train_raw[idx], cmap='gray')
        axes[0, digit].set_title(f"Label: {digit}", fontsize=8)
        axes[0, digit].axis('off')
        idx2 = np.where(y_train_raw == digit)[0][1]
        axes[1, digit].imshow(X_train_raw[idx2], cmap='gray')
        axes[1, digit].axis('off')
    plt.tight_layout()
    plt.savefig("unit1_sample_images.png", dpi=120, bbox_inches='tight')
    plt.show()
    print("Saved: unit1_sample_images.png")

    # Visualize class distribution
    fig, ax = plt.subplots(figsize=(10, 4))
    unique, counts = np.unique(y_train_raw, return_counts=True)
    unique_t, counts_t = np.unique(y_test_raw, return_counts=True)
    x = np.arange(10)
    ax.bar(x - 0.2, counts,   0.4, label='Training', color='steelblue', alpha=0.85)
    ax.bar(x + 0.2, counts_t, 0.4, label='Test',     color='tomato',    alpha=0.85)
    ax.set_xticks(x); ax.set_xticklabels([f'Digit {i}' for i in range(10)])
    ax.set_ylabel("Sample Count"); ax.set_title("Class Distribution", fontweight='bold')
    ax.legend(); plt.tight_layout()
    plt.savefig("unit1_class_distribution.png", dpi=120, bbox_inches='tight')
    plt.show()
    print("Saved: unit1_class_distribution.png")

    return (X_train, Y_train, y_train_labels,
            X_val,   Y_val,   y_val_labels,
            X_test_flat, Y_test_oh, y_test_raw)


# UNIT II: NEURAL NETWORK CONSTRUCTION (NumPy only)


# Activation Functions

def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return (Z > 0).astype(float)

def sigmoid(Z):
    return 1.0 / (1.0 + np.exp(-np.clip(Z, -500, 500)))

def sigmoid_derivative(Z):
    s = sigmoid(Z)
    return s * (1 - s)

def tanh_activation(Z):
    return np.tanh(Z)

def tanh_derivative(Z):
    return 1.0 - np.tanh(Z) ** 2

def softmax(Z):
    """Numerically stable softmax."""
    exp_Z = np.exp(Z - Z.max(axis=1, keepdims=True))
    return exp_Z / exp_Z.sum(axis=1, keepdims=True)

# Weight Initialization

def initialize_weights(layer_dims):
    """
    He initialization: W ~ N(0, sqrt(2/n_in))
    layer_dims: list of layer sizes, e.g. [784, 256, 128, 10]
    Returns: params dict with W1, b1, W2, b2, ...
    """
    np.random.seed(42)
    params = {}
    L = len(layer_dims) - 1
    for l in range(1, L + 1):
        n_in  = layer_dims[l - 1]
        n_out = layer_dims[l]
        params[f'W{l}'] = np.random.randn(n_in, n_out) * np.sqrt(2.0 / n_in)
        params[f'b{l}'] = np.zeros((1, n_out))
    return params

# Loss Function

def cross_entropy_loss(Y_hat, Y_true):
    """Categorical cross-entropy loss."""
    N = Y_true.shape[0]
    log_probs = -np.log(np.clip(Y_hat, 1e-15, 1.0))
    return np.sum(Y_true * log_probs) / N

def compute_accuracy(Y_hat, Y_true):
    predictions = np.argmax(Y_hat, axis=1)
    labels      = np.argmax(Y_true, axis=1)
    return np.mean(predictions == labels) * 100.0

# Forward Propagation

def forward_pass(X, params, activation='relu'):
    """
    Generic forward pass for a network with any number of hidden layers.
    All hidden layers use `activation`; output layer uses Softmax.
    Returns: Y_hat (output probabilities), cache (for backprop)
    """
    cache = {'A0': X}
    L = len([k for k in params if k.startswith('W')])

    act_fn = {'relu': relu, 'sigmoid': sigmoid, 'tanh': tanh_activation}[activation]

    for l in range(1, L):    # hidden layers
        A_prev = cache[f'A{l-1}']
        Z = A_prev.dot(params[f'W{l}']) + params[f'b{l}']
        A = act_fn(Z)
        cache[f'Z{l}'] = Z
        cache[f'A{l}'] = A

    # Output layer — always Softmax
    A_prev = cache[f'A{L-1}']
    Z_out  = A_prev.dot(params[f'W{L}']) + params[f'b{L}']
    A_out  = softmax(Z_out)
    cache[f'Z{L}'] = Z_out
    cache[f'A{L}'] = A_out

    return A_out, cache

# Backpropagation

def backward_pass(Y_true, params, cache, activation='relu'):
    """
    Compute gradients via backpropagation using the chain rule.
    Returns: grads dict with dW1, db1, dW2, db2, ...
    """
    grads = {}
    N = Y_true.shape[0]
    L = len([k for k in params if k.startswith('W')])

    act_deriv = {
        'relu':    relu_derivative,
        'sigmoid': sigmoid_derivative,
        'tanh':    tanh_derivative
    }[activation]

    # Output layer gradient (Softmax + Cross-Entropy combined simplifies to A - Y)
    dZ = cache[f'A{L}'] - Y_true       # (N, 10)
    grads[f'dW{L}'] = cache[f'A{L-1}'].T.dot(dZ) / N
    grads[f'db{L}'] = dZ.mean(axis=0, keepdims=True)

    # Hidden layer gradients (backprop through chain rule)
    for l in range(L - 1, 0, -1):
        dA = dZ.dot(params[f'W{l+1}'].T)
        dZ = dA * act_deriv(cache[f'Z{l}'])
        grads[f'dW{l}'] = cache[f'A{l-1}'].T.dot(dZ) / N
        grads[f'db{l}'] = dZ.mean(axis=0, keepdims=True)

    return grads

# Parameter Update (Mini-Batch Gradient Descent)

def update_params(params, grads, learning_rate):
    L = len([k for k in params if k.startswith('W')])
    for l in range(1, L + 1):
        params[f'W{l}'] -= learning_rate * grads[f'dW{l}']
        params[f'b{l}'] -= learning_rate * grads[f'db{l}']
    return params


# UNIT III: TRAINING, TESTING & EVALUATION


def train(X_train, Y_train, X_val, Y_val,
          layer_dims   = [784, 256, 128, 10],
          learning_rate= 0.01,
          epochs       = 50,
          batch_size   = 64,
          activation   = 'relu'):

    print("\n" + "=" * 60)
    print("UNIT III: Training")
    print(f"  Architecture : {' → '.join(map(str, layer_dims))}")
    print(f"  Learning rate: {learning_rate}  |  Epochs: {epochs}  |  Batch: {batch_size}")
    print("=" * 60)

    params = initialize_weights(layer_dims)
    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
    N = X_train.shape[0]

    for epoch in range(1, epochs + 1):
        perm = np.random.permutation(N)
        X_shuf, Y_shuf = X_train[perm], Y_train[perm]

        # Mini-batch gradient descent
        for start in range(0, N, batch_size):
            end  = min(start + batch_size, N)
            X_b  = X_shuf[start:end]
            Y_b  = Y_shuf[start:end]
            Y_hat, cache = forward_pass(X_b, params, activation)
            grads         = backward_pass(Y_b, params, cache, activation)
            params        = update_params(params, grads, learning_rate)

        # Compute epoch-level metrics
        Y_hat_tr, _ = forward_pass(X_train, params, activation)
        Y_hat_vl, _ = forward_pass(X_val,   params, activation)

        tl = cross_entropy_loss(Y_hat_tr, Y_train)
        vl = cross_entropy_loss(Y_hat_vl, Y_val)
        ta = compute_accuracy(Y_hat_tr, Y_train)
        va = compute_accuracy(Y_hat_vl, Y_val)

        history['train_loss'].append(tl)
        history['val_loss'].append(vl)
        history['train_acc'].append(ta)
        history['val_acc'].append(va)

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{epochs}  |  "
                  f"Train Loss: {tl:.4f}  Val Loss: {vl:.4f}  |  "
                  f"Train Acc: {ta:.2f}%  Val Acc: {va:.2f}%")

    return params, history


def plot_training_curves(history):
    """Plot loss and accuracy curves and save."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
    epochs = range(1, len(history['train_loss']) + 1)

    ax1.plot(epochs, history['train_loss'], label='Train Loss',      color='steelblue', lw=2)
    ax1.plot(epochs, history['val_loss'],   label='Validation Loss', color='tomato',    lw=2, linestyle='--')
    ax1.set_xlabel('Epoch'); ax1.set_ylabel('Cross-Entropy Loss')
    ax1.set_title('Loss vs. Epochs', fontweight='bold'); ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(epochs, history['train_acc'], label='Train Accuracy',      color='steelblue', lw=2)
    ax2.plot(epochs, history['val_acc'],   label='Validation Accuracy', color='darkorange', lw=2, linestyle='--')
    ax2.set_xlabel('Epoch'); ax2.set_ylabel('Accuracy (%)')
    ax2.set_title('Accuracy vs. Epochs', fontweight='bold'); ax2.legend()
    ax2.set_ylim([50, 102]); ax2.grid(True, alpha=0.3)

    plt.suptitle('Training Curves', fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig("unit3_training_curves.png", dpi=120, bbox_inches='tight')
    plt.show()
    print("Saved: unit3_training_curves.png")


def evaluate(params, X_test, Y_test, y_test_labels, activation='relu'):
    """Evaluate on test set and print full report."""
    print("\n" + "=" * 60)
    print("UNIT III: Evaluation on Test Set")
    print("=" * 60)

    Y_hat, _ = forward_pass(X_test, params, activation)
    preds     = np.argmax(Y_hat, axis=1)
    accuracy  = compute_accuracy(Y_hat, Y_test)

    print(f"\n  Test Accuracy: {accuracy:.2f}%")
    print(f"  Test Loss    : {cross_entropy_loss(Y_hat, Y_test):.4f}")

    # Confusion Matrix
    num_classes = 10
    cm = np.zeros((num_classes, num_classes), dtype=int)
    for true, pred in zip(y_test_labels, preds):
        cm[true, pred] += 1

    fig, ax = plt.subplots(figsize=(9, 8))
    im = ax.imshow(cm, cmap='Blues', interpolation='nearest')
    plt.colorbar(im, ax=ax)
    ax.set_xticks(range(10)); ax.set_yticks(range(10))
    ax.set_xticklabels(range(10)); ax.set_yticklabels(range(10))
    thresh = cm.max() / 2.0
    for i in range(10):
        for j in range(10):
            ax.text(j, i, str(cm[i, j]), ha='center', va='center', fontsize=9,
                    color='white' if cm[i, j] > thresh else 'black', fontweight='bold')
    ax.set_xlabel('Predicted Label', fontsize=12, fontweight='bold')
    ax.set_ylabel('True Label',      fontsize=12, fontweight='bold')
    ax.set_title(f'Confusion Matrix — Test Accuracy: {accuracy:.2f}%', fontweight='bold', fontsize=12)
    plt.tight_layout()
    plt.savefig("unit3_confusion_matrix.png", dpi=120, bbox_inches='tight')
    plt.show()
    print("Saved: unit3_confusion_matrix.png")

    # Per-class Precision, Recall, F1
    print(f"\n  {'Digit':<8} {'Precision':>12} {'Recall':>10} {'F1-Score':>10} {'Support':>10}")
    print("  " + "-" * 54)
    for c in range(num_classes):
        tp = cm[c, c]
        fp = cm[:, c].sum() - tp
        fn = cm[c, :].sum() - tp
        prec = tp / (tp + fp + 1e-9) * 100
        rec  = tp / (tp + fn + 1e-9) * 100
        f1   = 2 * prec * rec / (prec + rec + 1e-9)
        print(f"  {c:<8} {prec:>11.1f}% {rec:>9.1f}% {f1:>9.1f}% {cm[c,:].sum():>10}")

    return accuracy, cm


def save_model(params, filename='model.pkl'):
    """Save trained parameters using pickle."""
    with open(filename, 'wb') as f:
        pickle.dump(params, f)
    print(f"\n  Model saved to '{filename}'")


def load_model(filename='model.pkl'):
    """Load model parameters from pickle file."""
    with open(filename, 'rb') as f:
        params = pickle.load(f)
    print(f"  Model loaded from '{filename}'")
    return params


# UNIT IV: EXPERIMENTATION AND ANALYSIS


def run_experiments(X_train, Y_train, X_val, Y_val, X_test, Y_test, y_test_labels):
    print("\n" + "=" * 60)
    print("UNIT IV: Experimentation and Analysis")
    print("=" * 60)

    results = {}

    # Experiment A: Learning Rate
    print("\n[Experiment A] Learning Rate Sensitivity")
    lrs = [0.001, 0.005, 0.01, 0.05, 0.1]
    lr_results = {}
    for lr in lrs:
        params, hist = train(X_train, Y_train, X_val, Y_val,
                             layer_dims=[784, 256, 128, 10],
                             learning_rate=lr, epochs=30, batch_size=64)
        Y_hat, _ = forward_pass(X_test, params)
        acc = compute_accuracy(Y_hat, Y_test)
        lr_results[lr] = acc
        print(f"    LR={lr:.3f}  →  Test Accuracy: {acc:.2f}%")
    results['learning_rate'] = lr_results

    # Experiment B: Network Architecture
    print("\n[Experiment B] Architecture Depth / Width")
    architectures = {
        '784→10':               [784, 10],
        '784→64→10':            [784, 64, 10],
        '784→128→10':           [784, 128, 10],
        '784→256→128→10':       [784, 256, 128, 10],
        '784→512→256→10':       [784, 512, 256, 10],
    }
    arch_results = {}
    for name, dims in architectures.items():
        params, hist = train(X_train, Y_train, X_val, Y_val,
                             layer_dims=dims, learning_rate=0.01, epochs=30, batch_size=64)
        Y_hat, _ = forward_pass(X_test, params)
        acc = compute_accuracy(Y_hat, Y_test)
        arch_results[name] = acc
        print(f"    {name:<25}  →  Test Accuracy: {acc:.2f}%")
    results['architecture'] = arch_results

    # Experiment C: Activation Functions
    print("\n[Experiment C] Activation Function Comparison")
    activations = ['sigmoid', 'tanh', 'relu']
    act_results = {}
    for act in activations:
        params, hist = train(X_train, Y_train, X_val, Y_val,
                             layer_dims=[784, 256, 128, 10],
                             learning_rate=0.01, epochs=30, batch_size=64,
                             activation=act)
        Y_hat, _ = forward_pass(X_test, params, activation=act)
        acc = compute_accuracy(Y_hat, Y_test)
        act_results[act] = acc
        print(f"    {act:<12}  →  Test Accuracy: {acc:.2f}%")
    results['activation'] = act_results

    # Plot experiment results
    fig, axes = plt.subplots(1, 3, figsize=(14, 5))

    # Learning rate plot
    axes[0].plot(range(len(lrs)), list(lr_results.values()), 'o-', color='steelblue', lw=2.2, ms=9)
    axes[0].set_xticks(range(len(lrs))); axes[0].set_xticklabels([str(lr) for lr in lrs])
    axes[0].set_title('Learning Rate', fontweight='bold'); axes[0].set_ylabel('Test Accuracy (%)')
    axes[0].set_xlabel('Learning Rate'); axes[0].grid(True, alpha=0.3)

    # Architecture plot
    arch_names = ['No HL', '1×64', '1×128', '2×(256,128)', '2×(512,256)']
    axes[1].bar(range(len(arch_results)), list(arch_results.values()), color='steelblue', alpha=0.85, edgecolor='white')
    axes[1].set_xticks(range(len(arch_results))); axes[1].set_xticklabels(arch_names, rotation=15, ha='right', fontsize=8)
    axes[1].set_title('Network Architecture', fontweight='bold'); axes[1].set_ylabel('Test Accuracy (%)')
    axes[1].grid(axis='y', alpha=0.3)

    # Activation plot
    colors = ['gold', 'darkorange', 'steelblue']
    axes[2].bar(range(len(act_results)), list(act_results.values()), color=colors, alpha=0.85, edgecolor='white')
    axes[2].set_xticks(range(len(act_results))); axes[2].set_xticklabels(list(act_results.keys()))
    axes[2].set_title('Activation Functions', fontweight='bold'); axes[2].set_ylabel('Test Accuracy (%)')
    axes[2].grid(axis='y', alpha=0.3)

    for ax in axes: ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)

    plt.suptitle('Unit IV — Hyperparameter Experiments', fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig("unit4_experiments.png", dpi=120, bbox_inches='tight')
    plt.show()
    print("\nSaved: unit4_experiments.png")

    return results


def tensorflow_benchmark(X_train, Y_train, X_val, Y_val, X_test, y_test_labels,
                          epochs=30, batch_size=64):
    """Build and train an equivalent model using TensorFlow/Keras for benchmarking."""
    print("\n" + "=" * 60)
    print("UNIT IV: TensorFlow/Keras Benchmark")
    print("=" * 60)

    import tensorflow as tf

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation='relu', input_shape=(784,),
                              kernel_initializer='he_normal'),
        tf.keras.layers.Dense(128, activation='relu',
                              kernel_initializer='he_normal'),
        tf.keras.layers.Dense(10,  activation='softmax'),
    ])
    model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
                  loss='categorical_crossentropy', metrics=['accuracy'])

    print("\n  Training TensorFlow/Keras baseline...")
    history = model.fit(X_train, Y_train,
                        validation_data=(X_val, Y_val),
                        epochs=epochs, batch_size=batch_size, verbose=0)

    _, test_acc = model.evaluate(X_test, tf.keras.utils.to_categorical(y_test_labels), verbose=0)
    print(f"  TF/Keras Test Accuracy: {test_acc * 100:.2f}%")
    return test_acc * 100


# Run all units in sequence


if __name__ == '__main__':

    # Unit I: Load and preprocess data
    (X_train, Y_train, y_train_labels,
     X_val,   Y_val,   y_val_labels,
     X_test,  Y_test,  y_test_labels) = load_and_preprocess_data()

    # Unit II + III: Build and train the best model
    BEST_ARCH   = [784, 256, 128, 10]
    BEST_LR     = 0.01
    BEST_EPOCHS = 50
    BEST_BATCH  = 64

    params, history = train(X_train, Y_train, X_val, Y_val,
                            layer_dims    = BEST_ARCH,
                            learning_rate = BEST_LR,
                            epochs        = BEST_EPOCHS,
                            batch_size    = BEST_BATCH,
                            activation    = 'relu')

    plot_training_curves(history)

    # Unit III: Evaluate on test set
    test_acc, conf_matrix = evaluate(params, X_test, Y_test, y_test_labels)

    # Unit III: Save & reload model
    save_model(params, 'model.pkl')
    loaded_params = load_model('model.pkl')

    # Verify reload produces the same accuracy
    Y_hat_reload, _ = forward_pass(X_test, loaded_params)
    reload_acc = compute_accuracy(Y_hat_reload, Y_test)
    print(f"  Reloaded model accuracy: {reload_acc:.2f}%  ✓ (matches original)")

    # Unit IV: Experiments
    # NOTE: This runs many experiments and takes 10-20 minutes.
    # To skip experiments, comment out the two lines below.
    exp_results = run_experiments(X_train, Y_train, X_val, Y_val,
                                  X_test,  Y_test,  y_test_labels)

    # Unit IV: TensorFlow benchmark
    tf_acc = tensorflow_benchmark(X_train, Y_train, X_val, Y_val,
                                  X_test, y_test_labels, epochs=30)

    # Final Summary
    print("\n" + "=" * 60)
    print("FINAL SUMMARY")
    print("=" * 60)
    print(f"  Custom NumPy  Test Accuracy : {test_acc:.2f}%")
    print(f"  TF/Keras      Test Accuracy : {tf_acc:.2f}%")
    print(f"  Difference                  : {tf_acc - test_acc:.2f}%")
    print("=" * 60)
    print("\nOutput files:")
    for f in ['unit1_sample_images.png', 'unit1_class_distribution.png',
              'unit3_training_curves.png', 'unit3_confusion_matrix.png',
              'unit4_experiments.png', 'model.pkl']:
        exists = "✓" if os.path.exists(f) else "✗"
        print(f"  {exists}  {f}")